project_id = "enlxxeyzthcphnettkeu"

[functions.astro-chat]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.get-order-status]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false

[functions.daily-horoscope]
verify_jwt = false
